name: Release

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target:
          - aarch64-linux-musl
          - loongarch64-linux-musl
          - riscv32-linux-musl
          - riscv64-linux-musl
          - x86_64-linux-musl
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: true
      - name: Build ${{ matrix.target }}
        run: ./scripts/make ${{ matrix.target }}
      - name: Upload ${{ matrix.target }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ matrix.target }}.tgz
          asset_name: ${{ matrix.target }}.tgz
          asset_content_type: application/octet-stream
